[theme]
base = "light"
primaryColor = "#157649"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F8F4"
textColor = "#0C1F18"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
